# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 476e73f50f8d88944dbc8a8e8c935f9f926063188bc3bb715655c042ec718683e2fd99058e1ca6cdf0e6d810507069cc4e993a8b702ef180a0a0fe6a7efc0b71

test:
  secret_key_base: d7375e2196028cac4a103fe72c6f93d475ce7ea96b167a2a90dfc6087856e0bd76b231a16c21fb4c74c1e105405edc952a42fc7da9f2e290de85f87ff6bcd17c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
